name: ptnzzn_random
description: "A random app with 2 feature Yes or No and Spin wheel."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc:
  go_router: ^14.7.2
  flutter_fortune_wheel: ^1.3.2
  flutter_svg: ^2.0.17
  flutter_launcher_icons:
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  rxdart: ^0.28.0
  intl: ^0.19.0
  easy_localization: ^3.0.7+1
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_ico.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/translations/
